### ISSUE TITLE
npm run setup fails

### ISSUE THREAD

**Issue by Campbellb** [kelsonic/react-redux-material-ui-boilerplate#1]
When following the Quick Start instructions, `npm run setup` fails. 

`npm run setup` is looking to run `node ./internals/scripts/setup.js`, but that file doesn't exist in the current repo!

**Comment by kelsonic** [comment]
The `setup` and `clean` scripts have been deleted as there is no longer an example app that comes with the boilerplate. I've [updated the docs to reflect this](https://github.com/kelsonic/react-redux-material-ui-boilerplate/commit/d108afe30d5f004d478804d7870aa07cb058586a). Thanks for pointing this out! :)
